runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /permissions_init
  script: lmhcMain.app
  login: admin

- url: /insurance_init
  script: lmhcMain.app
  login: admin

- url: /.*
  script: lmhcMain.app
  login: required
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
