runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /static
  static_dir: static

- url: /.*_init
  script: lmhcMain.app
  login: admin

- url: /_ah/bounce
  script: bounceMail.app
  login: admin

- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin

- url: /.*
  script: lmhcMain.app
  login: required
  secure: always

# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pytz
  version: latest
# [END libraries]

inbound_services:
- mail
- mail_bounce
